CREATE TABLE Profiles (
    PROFILEID INT PRIMARY KEY IDENTITY(1,1),
    FOREIGN KEY (USERID) REFERENCES users(Id),
    BIO TEXT NOT NULL,
    IMAGE1 VARBINARY(MAX),
    IMAGE2 VARBINARY(MAX),
    IMAGE3 VARBINARY(MAX),
    OCCUPATION NVARCHAR(255),
    HOBBIES TEXT NOT NULL
);