CREATE TABLE Users (
    Id INT PRIMARY KEY IDENTITY(1,1),
    EMAIL NVARCHAR(255) NOT NULL,
    PASSWORD NVARCHAR(255) NOT NULL,
    FIRSTNAME NVARCHAR(255) NOT NULL,
    LASTNAME NVARCHAR(255) NOT NULL,
    GENDER CHAR(1) NOT NULL,
    DATEOFBIRTH DATE NOT NULL,
    CREATEDATE DATE
);